version 0.2

phases:
  install:
    runtime-versions:
      nodejs:18
    commands:
      - echo installing dependencies
      - cd app
      - npm install
  build:
    commands:
       - echo build completed
artifacts:
  files:
    - '**/*'
  base-directory: app
